services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./production.db
    volumes:
      - ./prisma/production.db:/app/prisma/production.db
